version: '3'
services:
  postgres:
    build:
      context: sql/.
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=optimizer
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
    - "80:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=postgres
