pipeline:
- link: 15
  model: m0
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 2
    memory: 3
- link: 12
  model: m1
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 7
    memory: 15
- link: 0
  model: m2
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 7
    memory: 7
- link: 0
  model: m3
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 7
    memory: 13
- link: 7
  model: m4
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 15
- link: 0
  model: m5
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 5
    memory: 4
- link: 6
  model: m6
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 1
    memory: 1
- link: 14
  model: m7
  privacy:
    location: US
    type: 0
  resources:
    cpus: 4
    memory: 1
- link: 7
  model: m8
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 4
    memory: 8
- link: 13
  model: m9
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 7
    memory: 15
- link: 9
  model: m10
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 7
    memory: 4
- link: 16
  model: m11
  privacy:
    location: US
    type: 2
  resources:
    cpus: 1
    memory: 11
- link: 18
  model: m12
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 4
    memory: 7
- link: 1
  model: m13
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 22
    memory: 48
- link: 13
  model: m14
  privacy:
    location: US
    type: 1
  resources:
    cpus: 4
    memory: 8
- link: 11
  model: m15
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 6
- link: 3
  model: m16
  privacy:
    location: US
    type: 2
  resources:
    cpus: 1
    memory: 15
- link: 11
  model: m17
  privacy:
    location: US
    type: 1
  resources:
    cpus: 7
    memory: 6
- link: 9
  model: m18
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 4
    memory: 1
- link: 5
  model: m19
  privacy:
    location: US
    type: 0
  resources:
    cpus: 6
    memory: 13
version: '1.0'
