pipeline:
- link: 63
  model: m0
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 2
    memory: 3
- link: 48
  model: m1
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 7
    memory: 15
- link: 3
  model: m2
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 7
    memory: 7
- link: 0
  model: m3
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 7
    memory: 13
- link: 29
  model: m4
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 15
- link: 2
  model: m5
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 5
    memory: 4
- link: 27
  model: m6
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 1
    memory: 1
- link: 56
  model: m7
  privacy:
    location: US
    type: 0
  resources:
    cpus: 4
    memory: 1
- link: 28
  model: m8
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 4
    memory: 8
- link: 53
  model: m9
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 7
    memory: 15
- link: 37
  model: m10
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 7
    memory: 4
- link: 64
  model: m11
  privacy:
    location: US
    type: 2
  resources:
    cpus: 1
    memory: 11
- link: 75
  model: m12
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 4
    memory: 7
- link: 4
  model: m13
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 22
    memory: 48
- link: 53
  model: m14
  privacy:
    location: US
    type: 1
  resources:
    cpus: 4
    memory: 8
- link: 47
  model: m15
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 6
- link: 13
  model: m16
  privacy:
    location: US
    type: 2
  resources:
    cpus: 1
    memory: 15
- link: 47
  model: m17
  privacy:
    location: US
    type: 1
  resources:
    cpus: 7
    memory: 6
- link: 39
  model: m18
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 4
    memory: 1
- link: 21
  model: m19
  privacy:
    location: US
    type: 0
  resources:
    cpus: 6
    memory: 13
- link: 69
  model: m20
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 23
    memory: 30
- link: 44
  model: m21
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 102
    memory: 123
- link: 70
  model: m22
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 7
    memory: 12
- link: 65
  model: m23
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 5
    memory: 1
- link: 26
  model: m24
  privacy:
    location: US
    type: 2
  resources:
    cpus: 32
    memory: 24
- link: 72
  model: m25
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 20
    memory: 19
- link: 62
  model: m26
  privacy:
    location: US
    type: 1
  resources:
    cpus: 5
    memory: 7
- link: 0
  model: m27
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 7
    memory: 12
- link: 3
  model: m28
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 5
    memory: 11
- link: 70
  model: m29
  privacy:
    location: US
    type: 0
  resources:
    cpus: 32
    memory: 30
- link: 32
  model: m30
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 5
    memory: 6
- link: 57
  model: m31
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 1
    memory: 3
- link: 14
  model: m32
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 33
    memory: 135
- link: 8
  model: m33
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 7
    memory: 6
- link: 21
  model: m34
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 2
    memory: 6
- link: 37
  model: m35
  privacy:
    location: US
    type: 2
  resources:
    cpus: 6
    memory: 9
- link: 14
  model: m36
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 4
    memory: 11
- link: 53
  model: m37
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 7
    memory: 35
- link: 32
  model: m38
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 7
    memory: 7
- link: 2
  model: m39
  privacy:
    location: US
    type: 1
  resources:
    cpus: 6
    memory: 7
- link: 4
  model: m40
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 60
    memory: 68
- link: 64
  model: m41
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 6
- link: 80
  model: m42
  privacy:
    location: US
    type: 0
  resources:
    cpus: 6
    memory: 14
- link: 3
  model: m43
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 7
    memory: 15
- link: 54
  model: m44
  privacy:
    location: US
    type: 2
  resources:
    cpus: 4
    memory: 11
- link: 6
  model: m45
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 1
    memory: 10
- link: 38
  model: m46
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 16
    memory: 20
- link: 32
  model: m47
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 6
    memory: 6
- link: 75
  model: m48
  privacy:
    location: US
    type: 0
  resources:
    cpus: 2
    memory: 1
- link: 21
  model: m49
  privacy:
    location: US
    type: 1
  resources:
    cpus: 7
    memory: 7
- link: 44
  model: m50
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 7
    memory: 2
- link: 55
  model: m51
  privacy:
    location: US
    type: 2
  resources:
    cpus: 1
    memory: 7
- link: 49
  model: m52
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 5
    memory: 7
- link: 78
  model: m53
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 3
    memory: 16
- link: 20
  model: m54
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 7
    memory: 13
- link: 43
  model: m55
  privacy:
    location: US
    type: 0
  resources:
    cpus: 2
    memory: 11
- link: 12
  model: m56
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 4
    memory: 7
- link: 68
  model: m57
  privacy:
    location: US
    type: 1
  resources:
    cpus: 7
    memory: 13
- link: 5
  model: m58
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 4
    memory: 8
- link: 68
  model: m59
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 1
    memory: 5
- link: 64
  model: m60
  privacy:
    location: ES
    type: 2
  resources:
    cpus: 2
    memory: 9
- link: 43
  model: m61
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 7
    memory: 9
- link: 62
  model: m62
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 1
    memory: 10
- link: 52
  model: m63
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 2
    memory: 4
- link: 43
  model: m64
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 1
    memory: 13
- link: 70
  model: m65
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 1
    memory: 13
- link: 37
  model: m66
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 2
    memory: 3
- link: 13
  model: m67
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 5
    memory: 4
- link: 78
  model: m68
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 32
    memory: 18
- link: 14
  model: m69
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 6
    memory: 1
- link: 75
  model: m70
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 32
    memory: 18
- link: 21
  model: m71
  privacy:
    location: IE
    type: 1
  resources:
    cpus: 4
    memory: 6
- link: 13
  model: m72
  privacy:
    location: IE
    type: 2
  resources:
    cpus: 6
    memory: 8
- link: 70
  model: m73
  privacy:
    location: US
    type: 1
  resources:
    cpus: 20
    memory: 40
- link: 26
  model: m74
  privacy:
    location: ES
    type: 0
  resources:
    cpus: 3
    memory: 16
- link: 1
  model: m75
  privacy:
    location: IE
    type: 0
  resources:
    cpus: 6
    memory: 11
- link: 40
  model: m76
  privacy:
    location: US
    type: 2
  resources:
    cpus: 32
    memory: 34
- link: 8
  model: m77
  privacy:
    location: ES
    type: 1
  resources:
    cpus: 4
    memory: 13
- link: 14
  model: m78
  privacy:
    location: US
    type: 1
  resources:
    cpus: 1
    memory: 11
- link: 60
  model: m79
  privacy:
    location: US
    type: 2
  resources:
    cpus: 3
    memory: 7
version: '1.0'
